/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutWarehouseIndexImport } from './routes/_layout/warehouse/index'
import { Route as LayoutUsersIndexImport } from './routes/_layout/users/index'
import { Route as LayoutOrdersIndexImport } from './routes/_layout/orders/index'
import { Route as LayoutMangementIndexImport } from './routes/_layout/mangement/index'
import { Route as LayoutDashboardIndexImport } from './routes/_layout/dashboard/index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutWarehouseIndexRoute = LayoutWarehouseIndexImport.update({
  path: '/warehouse/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutUsersIndexRoute = LayoutUsersIndexImport.update({
  path: '/users/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOrdersIndexRoute = LayoutOrdersIndexImport.update({
  path: '/orders/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMangementIndexRoute = LayoutMangementIndexImport.update({
  path: '/mangement/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardIndexRoute = LayoutDashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/mangement/': {
      id: '/_layout/mangement/'
      path: '/mangement'
      fullPath: '/mangement'
      preLoaderRoute: typeof LayoutMangementIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/orders/': {
      id: '/_layout/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof LayoutOrdersIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/users/': {
      id: '/_layout/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/warehouse/': {
      id: '/_layout/warehouse/'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof LayoutWarehouseIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LayoutRoute: LayoutRoute.addChildren({
    LayoutDashboardIndexRoute,
    LayoutMangementIndexRoute,
    LayoutOrdersIndexRoute,
    LayoutUsersIndexRoute,
    LayoutWarehouseIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/dashboard/",
        "/_layout/mangement/",
        "/_layout/orders/",
        "/_layout/users/",
        "/_layout/warehouse/"
      ]
    },
    "/_layout/dashboard/": {
      "filePath": "_layout/dashboard/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/mangement/": {
      "filePath": "_layout/mangement/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/orders/": {
      "filePath": "_layout/orders/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/users/": {
      "filePath": "_layout/users/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/warehouse/": {
      "filePath": "_layout/warehouse/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
